#!/bin/csh

setenv R_HOME /Library/Frameworks/R.framework/Resources
setenv R_LIBS /Library/Frameworks/R.framework/Versions/3.0/Resources/library
setenv R_LIBS_USER /Library/Frameworks/R.framework/Versions/3.0/Resources/library

./JGR-SL.app/Contents/MacOS/JGR

